[workspace]

members = [
    "car-utility",
    "cpp-transmit-example",
    "controller",
    "hyphae",
    "local-dev-environment/desktop/radio-service",
    "local-storage",
    "messages",
    "myceli"
]