[workspace]

members = [
    "app-api-cli",
    "block-streamer",
    "car-utility",
    "local-dev-environment/desktop/radio-service",
    "messages",
    "cpp-transmit-example",
    "local-storage"
]