[package]
name = "myceli"
version = "0.6.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
cid = {version = "0.10", features = ["scale-codec"] }
clap = { version = "4.0.15", features = ["derive"] }
local-storage = { path = "../local-storage" }
messages = { path = "../messages" }
serde_derive = "1"
serde = "1"
tokio = "1"
toml = "0.7"
tracing = "0.1"
tracing-subscriber = "0.3"
transports = { path = "../transports" }

[dev-dependencies]
assert_fs = "1"
blake2 = "0.10.6"
file-hashing = "0.1.1"
futures = "0.3.21"
iroh-unixfs = "0.2.0"
rand = "0.8"