[target.armv7-unknown-linux-gnueabihf]
dockerfile = "../cross-armv7-linux.Dockerfile"

[target.aarch64-unknown-linux-gnu]
dockerfile = "../cross-aarch64-linux.Dockerfile"

[target.x86_64-unknown-linux-gnu]
dockerfile = "../cross-x86-linux.Dockerfile"