[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
dirs = "5.0.1"
figment.workspace = true
log.workspace = true
messages.workspace = true
serde.workspace = true
transports.workspace = true
