[package]
name = "udp_forward"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-error.workspace = true
rand.workspace = true
chrono = "0.4.31"