name: Docker Testing
on: [ pull_request ]
jobs:
  test_docker_build:
    name: Test Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test build of myceli docker
        run: docker build -f myceli.Dockerfile .
