name: CI Linting
on: [pull_request]
jobs:
  clippy_check:
    name: Run clippy check
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - uses: actions/checkout@v3
      - id: rust
        run: echo "toolchain=$(cat rust-toolchain)" >> $GITHUB_OUTPUT
        shell: bash
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.rust.outputs.toolchain }}
          components: clippy
      - name: Run clippy
        run: cargo clippy --all
        shell: bash
