name: CI Unit Testing
on: [pull_request]
jobs:
  build_and_test:
    name: Build and test rust
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Build workspace
        run: cargo build --release
        shell: bash
      - name: Test workspace
        run: cargo test
        shell: bash
