name: CI Unit Testing
on: [ pull_request ]
jobs:
  build_and_test:
    name: Build and test rust
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build workspace
        run: cargo build --release --features big
        shell: bash
      - name: Test big
        run: cargo test --features big,proto_all
        shell: bash
      - name: Test small
        run: cargo test --features small,proto_all
        shell: bash
      - name: Test small ship
        run: cargo test --features small,proto_ship
        shell: bash
      - name: Test small sync
        run: cargo test --features small,proto_sync
        shell: bash
