name: CI Unit Testing
on: [pull_request]
jobs:
  build_and_test:
    name: Build and test rust
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build workspace
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Test workspace
        uses: actions-rs/cargo@v1
        with:
          command: test
